import { DoorOpen, Settings2, Users, Wind } from 'lucide-angular';
import { CarMockup } from '../types/carMockup';

export const CARS_MOCKUP: CarMockup[] = [
  {
    id: 1,
    brand: 'Porsche',
    model: '911 Carrera S',
    stars: 4.9,
    reviews: 128,
    image: '/cars-mockups/porsche-911-carrera.png',
    specs: [
      { label: '2 Passengers', icon: Users },
      { label: 'Automatic', icon: Settings2 },
      { label: 'Dual Zone AC', icon: Wind },
      { label: '2 Doors', icon: DoorOpen },
    ],
    pricePerDay: 250,
  },
  {
    id: 2,
    brand: 'Audi',
    model: 'RS e-tron GT',
    stars: 4.8,
    reviews: 95,
    image: '/cars-mockups/audi-e-tron-gt.png',
    specs: [
      { label: '4 Passengers', icon: Users },
      { label: 'Automatic', icon: Settings2 },
      { label: 'Tri-Zone AC', icon: Wind },
      { label: '4 Doors', icon: DoorOpen },
    ],
    pricePerDay: 180,
  },
  {
    id: 3,
    brand: 'BMW',
    model: 'M4 Competition',
    stars: 4.7,
    reviews: 112,
    image: '/cars-mockups/bmw-m4-competition.png',
    specs: [
      { label: '4 Passengers', icon: Users },
      { label: 'Automatic', icon: Settings2 },
      { label: 'Dual Zone AC', icon: Wind },
      { label: '2 Doors', icon: DoorOpen },
    ],
    pricePerDay: 210,
  },
  {
    id: 4,
    brand: 'Mercedes',
    model: 'G-Class G63',
    stars: 4.9,
    reviews: 84,
    image: '/cars-mockups/mercedes-classe-g.png',
    specs: [
      { label: '5 Passengers', icon: Users },
      { label: 'Automatic', icon: Settings2 },
      { label: 'Multi-Zone AC', icon: Wind },
      { label: '5 Doors', icon: DoorOpen },
    ],
    pricePerDay: 320,
  },
  {
    id: 5,
    brand: 'Volkswagen',
    model: 'Golf 8',
    stars: 4.5,
    reviews: 210,
    image: '/cars-mockups/volkswagen-golf.png',
    specs: [
      { label: '5 Passengers', icon: Users },
      { label: 'Manual', icon: Settings2 },
      { label: 'Standard AC', icon: Wind },
      { label: '5 Doors', icon: DoorOpen },
    ],
    pricePerDay: 75,
  },
  {
    id: 6,
    brand: 'Hyundai',
    model: 'Ioniq 5 N',
    stars: 4.6,
    reviews: 67,
    image: '/cars-mockups/hyundai-ioniq.png',
    specs: [
      { label: '5 Passengers', icon: Users },
      { label: 'Automatic', icon: Settings2 },
      { label: 'Dual Zone AC', icon: Wind },
      { label: '5 Doors', icon: DoorOpen },
    ],
    pricePerDay: 110,
  },
  {
    id: 7,
    brand: 'Skoda',
    model: 'Fabia',
    stars: 4.4,
    reviews: 156,
    image: '/cars-mockups/skoda-fabia.png',
    specs: [
      { label: '5 Passengers', icon: Users },
      { label: 'Automatic', icon: Settings2 },
      { label: 'Dual Zone AC', icon: Wind },
      { label: '5 Doors', icon: DoorOpen },
    ],
    pricePerDay: 90,
  },
  {
    id: 8,
    brand: 'Peugeot',
    model: '208',
    stars: 4.5,
    reviews: 42,
    image: '/cars-mockups/peugeot-208.png',
    specs: [
      { label: '5 Passengers', icon: Users },
      { label: 'Automatic', icon: Settings2 },
      { label: 'Dual Zone AC', icon: Wind },
      { label: '5 Doors', icon: DoorOpen },
    ],
    pricePerDay: 130,
  },
];
