import { CarStatus, CarType, Transmission } from "@/generated/prisma/enums";
import { createCarBody } from "@/types/car.type";

export interface Car extends Omit<createCarBody, "brandId"> {
  brand_name: string;
}

export const CARS: Car[] = [
  // FIAT
  {
    brand_name: "fiat",
    model: "Panda 2019",
    year: 2019,
    pricePerDay: 30,
    doors: 5,
    seats: 4,
    image: "https://example.com/images/panda.jpg",
    features: ["air conditioning", "radio", "ABS"],
    transmission: Transmission.MANUAL,
    type: CarType.HATCHBACK,
    status: CarStatus.AVAILABLE,
  },
  {
    brand_name: "fiat",
    model: "500 2020",
    year: 2020,
    pricePerDay: 35,
    doors: 3,
    seats: 4,
    image: "https://example.com/images/500.jpg",
    features: ["Bluetooth", "USB", "city steering"],
    transmission: Transmission.MANUAL,
    type: CarType.HATCHBACK,
    status: CarStatus.AVAILABLE,
  },
  {
    brand_name: "fiat",
    model: "Tipo 2021",
    year: 2021,
    pricePerDay: 45,
    doors: 4,
    seats: 5,
    image: "https://example.com/images/tipo.jpg",
    features: ["air conditioning", "cruise control", "parking sensors"],
    transmission: Transmission.MANUAL,
    type: CarType.SEDAN,
    status: CarStatus.AVAILABLE,
  },

  // VOLKSWAGEN
  {
    brand_name: "volkswagen",
    model: "Golf 2020",
    year: 2020,
    pricePerDay: 50,
    doors: 5,
    seats: 5,
    image: "https://example.com/images/golf.jpg",
    features: ["Bluetooth", "adaptive cruise control", "lane assist"],
    transmission: Transmission.AUTOMATIC,
    type: CarType.HATCHBACK,
    status: CarStatus.AVAILABLE,
  },
  {
    brand_name: "volkswagen",
    model: "Polo 2019",
    year: 2019,
    pricePerDay: 40,
    doors: 5,
    seats: 5,
    image: "https://example.com/images/polo.jpg",
    features: ["air conditioning", "radio", "ABS"],
    transmission: Transmission.MANUAL,
    type: CarType.HATCHBACK,
    status: CarStatus.AVAILABLE,
  },
  {
    brand_name: "volkswagen",
    model: "Tiguan 2021",
    year: 2021,
    pricePerDay: 65,
    doors: 5,
    seats: 5,
    image: "https://example.com/images/tiguan.jpg",
    features: ["navigation system", "rear camera", "parking sensors"],
    transmission: Transmission.AUTOMATIC,
    type: CarType.SUV,
    status: CarStatus.AVAILABLE,
  },

  // HONDA
  {
    brand_name: "honda",
    model: "Civic 2020",
    year: 2020,
    pricePerDay: 50,
    doors: 4,
    seats: 5,
    image: "https://example.com/images/civic.jpg",
    features: ["Bluetooth", "cruise control", "lane assist"],
    transmission: Transmission.AUTOMATIC,
    type: CarType.SEDAN,
    status: CarStatus.AVAILABLE,
  },
  {
    brand_name: "honda",
    model: "Jazz 2018",
    year: 2018,
    pricePerDay: 35,
    doors: 5,
    seats: 5,
    image: "https://example.com/images/jazz.jpg",
    features: ["air conditioning", "radio", "ABS"],
    transmission: Transmission.MANUAL,
    type: CarType.HATCHBACK,
    status: CarStatus.AVAILABLE,
  },
  {
    brand_name: "honda",
    model: "HR-V 2021",
    year: 2021,
    pricePerDay: 60,
    doors: 5,
    seats: 5,
    image: "https://example.com/images/hrv.jpg",
    features: ["rear camera", "Bluetooth", "parking sensors"],
    transmission: Transmission.AUTOMATIC,
    type: CarType.SUV,
    status: CarStatus.AVAILABLE,
  },

  // TOYOTA
  {
    brand_name: "toyota",
    model: "Yaris 2020",
    year: 2020,
    pricePerDay: 35,
    doors: 5,
    seats: 5,
    image: "https://example.com/images/yaris.jpg",
    features: ["hybrid system", "Bluetooth", "lane assist"],
    transmission: Transmission.AUTOMATIC,
    type: CarType.HATCHBACK,
    status: CarStatus.AVAILABLE,
  },
  {
    brand_name: "toyota",
    model: "Corolla 2021",
    year: 2021,
    pricePerDay: 50,
    doors: 4,
    seats: 5,
    image: "https://example.com/images/corolla.jpg",
    features: ["navigation system", "adaptive cruise control", "Bluetooth"],
    transmission: Transmission.AUTOMATIC,
    type: CarType.SEDAN,
    status: CarStatus.AVAILABLE,
  },
  {
    brand_name: "toyota",
    model: "C-HR 2021",
    year: 2021,
    pricePerDay: 60,
    doors: 5,
    seats: 5,
    image: "https://example.com/images/chr.jpg",
    features: ["hybrid system", "rear camera", "parking sensors"],
    transmission: Transmission.AUTOMATIC,
    type: CarType.SUV,
    status: CarStatus.AVAILABLE,
  },

  // FORD
  {
    brand_name: "ford",
    model: "Fiesta 2019",
    year: 2019,
    pricePerDay: 35,
    doors: 5,
    seats: 5,
    image: "https://example.com/images/fiesta.jpg",
    features: ["air conditioning", "Bluetooth", "ABS"],
    transmission: Transmission.MANUAL,
    type: CarType.HATCHBACK,
    status: CarStatus.AVAILABLE,
  },
  {
    brand_name: "ford",
    model: "Focus 2020",
    year: 2020,
    pricePerDay: 45,
    doors: 5,
    seats: 5,
    image: "https://example.com/images/focus.jpg",
    features: ["cruise control", "parking sensors", "Bluetooth"],
    transmission: Transmission.MANUAL,
    type: CarType.HATCHBACK,
    status: CarStatus.AVAILABLE,
  },
  {
    brand_name: "ford",
    model: "Kuga 2021",
    year: 2021,
    pricePerDay: 60,
    doors: 5,
    seats: 5,
    image: "https://example.com/images/kuga.jpg",
    features: ["hybrid system", "navigation system", "rear camera"],
    transmission: Transmission.AUTOMATIC,
    type: CarType.SUV,
    status: CarStatus.AVAILABLE,
  },

  // RENAULT
  {
    brand_name: "renault",
    model: "Clio 2020",
    year: 2020,
    pricePerDay: 35,
    doors: 5,
    seats: 5,
    image: "https://example.com/images/clio.jpg",
    features: ["air conditioning", "Bluetooth", "ABS"],
    transmission: Transmission.MANUAL,
    type: CarType.HATCHBACK,
    status: CarStatus.AVAILABLE,
  },
  {
    brand_name: "renault",
    model: "Megane 2021",
    year: 2021,
    pricePerDay: 45,
    doors: 5,
    seats: 5,
    image: "https://example.com/images/megane.jpg",
    features: ["cruise control", "parking sensors", "Bluetooth"],
    transmission: Transmission.MANUAL,
    type: CarType.HATCHBACK,
    status: CarStatus.AVAILABLE,
  },
  {
    brand_name: "renault",
    model: "Captur 2021",
    year: 2021,
    pricePerDay: 55,
    doors: 5,
    seats: 5,
    image: "https://example.com/images/captur.jpg",
    features: ["rear camera", "navigation system", "Bluetooth"],
    transmission: Transmission.AUTOMATIC,
    type: CarType.SUV,
    status: CarStatus.AVAILABLE,
  },

  // BMW
  {
    brand_name: "bmw",
    model: "Series 1 2020",
    year: 2020,
    pricePerDay: 65,
    doors: 5,
    seats: 5,
    image: "https://example.com/images/bmw1.jpg",
    features: ["navigation system", "Bluetooth", "parking sensors"],
    transmission: Transmission.AUTOMATIC,
    type: CarType.HATCHBACK,
    status: CarStatus.AVAILABLE,
  },
  {
    brand_name: "bmw",
    model: "Series 3 2021",
    year: 2021,
    pricePerDay: 80,
    doors: 4,
    seats: 5,
    image: "https://example.com/images/bmw3.jpg",
    features: ["leather seats", "navigation system", "cruise control"],
    transmission: Transmission.AUTOMATIC,
    type: CarType.SEDAN,
    status: CarStatus.AVAILABLE,
  },

  // MERCEDES
  {
    brand_name: "mercedes-benz",
    model: "A-Class 2020",
    year: 2020,
    pricePerDay: 75,
    doors: 5,
    seats: 5,
    image: "https://example.com/images/a_class.jpg",
    features: ["MBUX system", "Bluetooth", "navigation system"],
    transmission: Transmission.AUTOMATIC,
    type: CarType.HATCHBACK,
    status: CarStatus.AVAILABLE,
  },

  // AUDI
  {
    brand_name: "audi",
    model: "A3 2020",
    year: 2020,
    pricePerDay: 70,
    doors: 5,
    seats: 5,
    image: "https://example.com/images/a3.jpg",
    features: ["virtual cockpit", "Bluetooth", "parking sensors"],
    transmission: Transmission.AUTOMATIC,
    type: CarType.HATCHBACK,
    status: CarStatus.AVAILABLE,
  },

  // HYUNDAI
  {
    brand_name: "hyundai",
    model: "i30 2020",
    year: 2020,
    pricePerDay: 40,
    doors: 5,
    seats: 5,
    image: "https://example.com/images/i30.jpg",
    features: ["air conditioning", "Bluetooth", "lane assist"],
    transmission: Transmission.MANUAL,
    type: CarType.HATCHBACK,
    status: CarStatus.AVAILABLE,
  },

  // KIA
  {
    brand_name: "kia",
    model: "Sportage 2021",
    year: 2021,
    pricePerDay: 55,
    doors: 5,
    seats: 5,
    image: "https://example.com/images/sportage.jpg",
    features: ["navigation system", "rear camera", "Bluetooth"],
    transmission: Transmission.AUTOMATIC,
    type: CarType.SUV,
    status: CarStatus.AVAILABLE,
  },

  // NISSAN
  {
    brand_name: "nissan",
    model: "Qashqai 2020",
    year: 2020,
    pricePerDay: 55,
    doors: 5,
    seats: 5,
    image: "https://example.com/images/qashqai.jpg",
    features: ["parking sensors", "rear camera", "Bluetooth"],
    transmission: Transmission.AUTOMATIC,
    type: CarType.SUV,
    status: CarStatus.AVAILABLE,
  },

  // MAZDA
  {
    brand_name: "mazda",
    model: "Mazda3 2020",
    year: 2020,
    pricePerDay: 45,
    doors: 5,
    seats: 5,
    image: "https://example.com/images/mazda3.jpg",
    features: ["head-up display", "Bluetooth", "cruise control"],
    transmission: Transmission.MANUAL,
    type: CarType.HATCHBACK,
    status: CarStatus.AVAILABLE,
  },

  // CHEVROLET
  {
    brand_name: "chevrolet",
    model: "Spark 2019",
    year: 2019,
    pricePerDay: 30,
    doors: 5,
    seats: 4,
    image: "https://example.com/images/spark.jpg",
    features: ["radio", "ABS", "air conditioning"],
    transmission: Transmission.MANUAL,
    type: CarType.HATCHBACK,
    status: CarStatus.AVAILABLE,
  },

  // TESLA
  {
    brand_name: "tesla",
    model: "Model 3 2021",
    year: 2021,
    pricePerDay: 90,
    doors: 4,
    seats: 5,
    image: "https://example.com/images/model3.jpg",
    features: ["autopilot", "electric", "navigation system"],
    transmission: Transmission.AUTOMATIC,
    type: CarType.SEDAN,
    status: CarStatus.AVAILABLE,
  },
];
